version: '3.8'
services:
  airflow-webserver:
    image: apache/airflow:2.7.1-python3.11
    command: webserver
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./requirements.txt:/requirements.txt
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - _PIP_ADDITIONAL_REQUIREMENTS=pandas sqlalchemy pymysql apache-airflow-providers-mysql
    user: "${AIRFLOW_UID:-1000}:0"

  airflow-scheduler:
    image: apache/airflow:2.7.1-python3.11
    command: scheduler
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./requirements.txt:/requirements.txt
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - _PIP_ADDITIONAL_REQUIREMENTS=pandas sqlalchemy pymysql apache-airflow-providers-mysql
    user: "${AIRFLOW_UID:-1000}:0"

  airflow-init:
    image: apache/airflow:2.7.1-python3.11
    command: version
    environment:
      - _PIP_ADDITIONAL_REQUIREMENTS=pandas sqlalchemy pymysql apache-airflow-providers-mysql