version: '3.8'
services:
  # --- DATABASE: MySQL 8.0 ---
  mysql-db:
    image: mysql:8.0
    container_name: bpom_mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE_METADATA}
      - MYSQL_USER=${MYSQL_USER_AIRFLOW}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD_AIRFLOW}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- DATABASE GUI ---
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: bpom_phpmyadmin
    depends_on:
      - mysql-db
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mysql-db
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  # --- AIRFLOW: Initialize Database & Identity ---
  airflow-init:
    image: apache/airflow:2.7.1
    container_name: bpom_airflow_init
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=mysql+mysqldb://${MYSQL_USER_AIRFLOW}:${MYSQL_PASSWORD_AIRFLOW}@mysql-db:3306/${MYSQL_DATABASE_METADATA}
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - _AIRFLOW_WWW_USER_USERNAME=${_AIRFLOW_WWW_USER_USERNAME}
      - _AIRFLOW_WWW_USER_PASSWORD=${_AIRFLOW_WWW_USER_PASSWORD}
    command: >
      bash -c "airflow db init &&
      airflow users create --username admin --firstname BPOM --lastname Magang --role Admin --email magang@bpom.go.id --password admin || true"

  # --- AIRFLOW: Webserver ---
  airflow-webserver:
    image: apache/airflow:2.7.1
    container_name: bpom_airflow_webserver
    restart: always
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      
      # --- KONEKSI INTERNAL (Metadata) ---
      # Menggunakan airflow_user & airflow_pass dari .env
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=mysql+mysqldb://${MYSQL_USER_AIRFLOW}:${MYSQL_PASSWORD_AIRFLOW}@mysql-db:3306/${MYSQL_DATABASE_METADATA}
      
      # --- KONEKSI ETL (Imitasi User Khusus) ---
      # Menggunakan etl_worker_bpom & etl_password_456 sesuai 'id user khusus.sql'
      - AIRFLOW_CONN_MYSQL_SOURCE=mysql://etl_worker_bpom:etl_password_456@host.docker.internal:3306/db_monitoring_bpom
      - AIRFLOW_CONN_MYSQL_STAGING=mysql://etl_worker_bpom:etl_password_456@host.docker.internal:3306/db_dashboard_bpom_staging
    
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    command: webserver

  # --- AIRFLOW: Scheduler ---
  airflow-scheduler:
    image: apache/airflow:2.7.1
    container_name: bpom_airflow_scheduler
    restart: always
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment:
       - AIRFLOW__CORE__EXECUTOR=LocalExecutor
       - AIRFLOW__CORE__LOAD_EXAMPLES=False
      
      # --- KONEKSI INTERNAL (Metadata) ---
      # Menggunakan airflow_user & airflow_pass dari .env
       - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=mysql+mysqldb://${MYSQL_USER_AIRFLOW}:${MYSQL_PASSWORD_AIRFLOW}@mysql-db:3306/${MYSQL_DATABASE_METADATA}
      
      # --- KONEKSI ETL (Imitasi User Khusus) ---
      # Menggunakan etl_worker_bpom & etl_password_456 sesuai 'id user khusus.sql'
       - AIRFLOW_CONN_MYSQL_SOURCE=mysql://etl_worker_bpom:etl_password_456@host.docker.internal:3306/db_monitoring_bpom
       - AIRFLOW_CONN_MYSQL_STAGING=mysql://etl_worker_bpom:etl_password_456@host.docker.internal:3306/db_dashboard_bpom_staging
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
    command: scheduler